<?php
/**
 * This file is part of the {@link http://ontowiki.net OntoWiki} project.
 *
 * @copyright Copyright (c) 2011, {@link http://aksw.org AKSW}
 * @license http://opensource.org/licenses/gpl-license.php GNU General Public License (GPL)
 */

/**
 * Upload Template for the OntoWiki Files Extension
 *
 * @category OntoWiki
 * @package  OntoWiki_extensions_files
 * @author   Norman Radtke  <norman.radtke@gmail.com>
 */

$url  = new OntoWiki_Url(
    array(
        'controller' => 'linkandcreate',
        'action' => 'submit'
    ),
    array()
);
?>
<form action="<?php echo $url ?>" method="post">
    <select id="linkCandidates" name="candidates" >
        <option value="ignore">Please select a connection</option>
        <?php foreach ($this->linkData as $canditate): ?>
            <option value="<?php echo($this->resourceUri . 'öÖ'
                . $canditate['property'] . 'öÖ'
                . $canditate['class'] )
            ?>">
                <?php echo $canditate['propertyLabel'] ?>
                 zu
                <?php echo $canditate['classLabel'] ?>
            </option>
        <?php endforeach ?>
    </select>
    <a class="minibutton" id="linkandcreateSubmit">Submit</a>
</form>
